""" version which can be consumed from within the module """
VERSION_STR = "0.0.5"
DESCRIPTION = "pymultienv is a command to help you deal with multiple python environments"
APP_NAME = "pymultienv"
LOGGER_NAME = "pymultienv"
